# $schema: https://render.com/schema/render.yaml.json
version: "1"
services:

  - type: keyvalue
    plan: free
    region: ohio
    name: searxng-cache
    ipAllowList: []

  - type: web
    plan: free
    region: ohio
    name: searxng
    runtime: image
    image:
      url: ghcr.io/cybardev/searxng-instance:main
    envVars:
      - key: SEARXNG_SECRET
        generateValue: true
      - key: SEARXNG_VALKEY_URL
        fromService:
          name: searxng-cache
          type: keyvalue
          property: connectionString
